server:
  addr: "0.0.0.0:8080"

elasticsearch:
  hosts:
    - "http://elasticsearch1:9200"
    - "http://elasticsearch2:9200"
    - "http://elasticsearch3:9200"

rate_limit:
  global:
    rps: 10000
  search:
    rps: 5000
    burst: 10000

redis:
  addr: "redis:6379"
  password: ""
  db: 0
  ttl: 3600
